[2020-04-18 21:29:56,376]{/home/alta8/.local/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /conversion/con [GET]
Traceback (most recent call last):
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta8/Documents/RESTAPI/blueprints/conversion/resources.py", line 25, in get
    response = requests.get(self.url + '/current', params={'data_list': data_list, 'key':x_rapidapi_key})
NameError: name 'data_list' is not defined
[2020-04-18 21:29:56,379]{/home/alta8/Documents/RESTAPI/blueprints/__init__.py:66} ERROR - 
[2020-04-18 21:30:22,628]{/home/alta8/Documents/RESTAPI/blueprints/__init__.py:62} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/conversion/con?currency=USD", "request": null, "response": {"message": "Missing RapidAPI application key. Go to https://docs.rapidapi.com/docs/keys to learn how to get your API application key."}}
[2020-04-18 21:31:05,929]{/home/alta8/.local/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /conversion/con [GET]
Traceback (most recent call last):
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta8/Documents/RESTAPI/blueprints/conversion/resources.py", line 14, in get
    parser.add_argumen('currency', location='args', default=None)
AttributeError: 'RequestParser' object has no attribute 'add_argumen'
[2020-04-18 21:31:05,932]{/home/alta8/Documents/RESTAPI/blueprints/__init__.py:66} ERROR - 
[2020-04-18 21:31:15,927]{/home/alta8/.local/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /conversion/con [GET]
Traceback (most recent call last):
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta8/Documents/RESTAPI/blueprints/conversion/resources.py", line 14, in get
    parser.add_argumen('currency', location='args', default=None)
AttributeError: 'RequestParser' object has no attribute 'add_argumen'
[2020-04-18 21:31:15,928]{/home/alta8/Documents/RESTAPI/blueprints/__init__.py:66} ERROR - 
[2020-04-18 21:31:17,210]{/home/alta8/.local/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /conversion/con [GET]
Traceback (most recent call last):
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta8/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta8/Documents/RESTAPI/blueprints/conversion/resources.py", line 14, in get
    parser.add_argumen('currency', location='args', default=None)
AttributeError: 'RequestParser' object has no attribute 'add_argumen'
[2020-04-18 21:31:17,211]{/home/alta8/Documents/RESTAPI/blueprints/__init__.py:66} ERROR - 
[2020-04-18 21:31:46,922]{/home/alta8/Documents/RESTAPI/blueprints/__init__.py:62} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/conversion/con?", "request": null, "response": ["USD => 0.992321", "EUR => 0.912445", "GBP => 0.793596", "CAD => 1.389137", "ARS => 65.309597", "AUD => 1.559044", "BRL => 5.194879", "CLP => 846.740460", "CNY => 7.018669", "CYP => 2.493901", "CZK => 24.858290", "DKK => 6.807767", "EEK => 14.042086", "HKD => 7.691096", "HUF => 322.144343", "ISK => 142.794317", "INR => 75.927597", "JMD => 134.532967", "JPY => 106.726955", "LVL => 0.630730", "LTL => 3.098716", "MTL => 3.381036", "MXN => 23.545783", "NZD => 1.645225", "NOK => 10.250716", "PLN => 4.123553", "SGD => 1.411104", "SKK => 0.046044", "SIT => 0.005656", "ZAR => 18.654676", "KRW => 1206.892813", "SEK => 9.907453", "CHF => 0.959533", "TWD => 29.819654", "UYU => 42.913200", "MYR => 4.336421", "BSD => 0.992321", "CRC => 565.614963", "RON => 4.412039", "PHP => 50.422280", "AED => 3.644298", "VEB => 9910.816949", "IDR => 15446.000000", "TRY => 6.877217", "THB => 32.296319", "TTD => 6.687247", "ILS => 3.562450", "SYP => 510.479215", "XCD => 2.681759", "COP => 3913.614929", "RUB => 73.487262", "HRK => 6.896287", "KZT => 423.646774", "TZS => 2298.139495", "XPT => 0.001283", "SAR => 3.721197", "NIO => 34.100597", "LAK => 8856.288406", "OMR => 0.381547", "AMD => 480.372821", "CDF => 1701.816251", "KPW => 893.089385", "SPL => 0.165387", "KES => 105.777345", "ZWD => 359.121359", "KHR => 4023.976071", "MVR => 15.289710", "GTQ => 7.631943", "BZD => 1.989448", "BYR => 24179.409477", "LYD => 1.398899", "DZD => 127.118399", "BIF => 1891.478225", "GIP => 0.793596", "BOB => 6.822745", "XOF => 598.526211", "STD => 22520.647781", "NGN => 383.462548", "PGK => 3.430928", "ERN => 14.884801", "MWK => 730.592934", "CUP => 26.296529", "GMD => 50.631441", "CVE => 100.615722", "BTN => 75.927597", "XAF => 598.526211", "UGX => 3745.015670", "MAD => 10.128976", "MNT => 2764.832623", "LSL => 18.654676", "XAG => 0.065290", "TOP => 2.383369", "SHP => 0.793596", "RSD => 107.299125", "HTG => 94.784754", "MGA => 3718.575807", "MZN => 66.605847", "FKP => 0.793596", "BWP => 11.950428", "HNL => 24.651477", "PYG => 6417.013477", "JEP => 0.793596", "EGP => 15.629237", "LBP => 1495.923038", "ANG => 1.772900", "WST => 2.717510", "TVD => 1.559044", "GYD => 208.164142", "GGP => 0.793596", "NPR => 122.053195", "KMF => 448.896012", "IRR => 41702.375973", "XPD => 0.000458", "SRD => 7.400076", "TMM => 17402.385163", "SZL => 18.654676", "MOP => 7.921833", "BMD => 0.992321", "XPF => 108.884084", "ETB => 32.993658", "JOD => 0.703554", "MDL => 17.472832", "MRO => 370.068637", "YER => 248.390003", "BAM => 1.784595", "AWG => 1.776254", "PEN => 3.381566", "VEF => 9.910817", "SLL => 9558.915211", "KYD => 0.813704", "AOA => 558.035219", "TND => 2.860455", "TJS => 10.170793", "SCR => 17.288417", "LKR => 190.502989", "DJF => 176.722002", "GNF => 9482.551311", "VUV => 120.231874", "SDG => 54.714005", "IMP => 0.793596", "GEL => 3.114834", "FJD => 2.252678", "DOP => 53.971823", "XDR => 0.727945", "MUR => 39.480888", "MMK => 1409.788539", "LRD => 196.277577", "BBD => 1.984641", "ZMK => 18477.900661", "XAU => 0.000589", "VND => 23264.092196", "UAH => 26.847773", "TMT => 3.480483", "IQD => 1181.045753", "BGN => 1.784595", "KGS => 79.391995", "RWF => 929.060797", "BHD => 0.373113", "UZS => 10030.805925", "PKR => 164.974596", "MKD => 56.195383", "AFN => 75.567951", "NAD => 18.654676", "BDT => 84.075724", "AZN => 1.686037", "SOS => 571.376242", "QAR => 3.612050", "PAB => 0.992321", "CUC => 0.992321", "SVC => 8.682783", "SBD => 8.235025", "ALL => 113.737446", "BND => 1.411104", "KWD => 0.309356", "GHS => 5.754284", "ZMW => 18.477901", "XBT => 0.000140", "NTD => 29.427725", "BYN => 2.417941", "CNH => 7.021699", "MRU => 37.006864", "STN => 22.520648", "VES => 124425.632303", "MXV => 3.668671"]}
[2020-04-18 21:33:27,378]{/home/alta8/Documents/RESTAPI/blueprints/__init__.py:62} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/conversion/con?currency=USD", "request": null, "response": ["USD => 0.992321"]}
[2020-04-18 21:33:42,949]{/home/alta8/Documents/RESTAPI/blueprints/__init__.py:62} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/conversion/con?currency=INR", "request": null, "response": ["INR => 75.927597"]}
[2020-04-19 09:30:26,003]{/home/andrenovado/Documents/Coding/Alterra/andre_derby_restful_api/blueprints/__init__.py:62} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/conversion/con?currency=USD", "request": null, "response": ["USD => 0.992321"]}
